/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#444655",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed": "#ffd9e2",
        "tertiary-container": "#b5e5eb",
        "surface-bright": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed": "#e1e1f5",
        "secondary-container": "#e1e1f5",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#191b29",
        "surface-dim": "#d9dadb",
        "on-surface-variant": "#4f4446",
        "on-tertiary-container": "#39686d",
        "on-tertiary-fixed": "#001f23",
        "on-surface": "#191c1d",
        "outline-variant": "#d3c3c5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c5c5d8",
        "surface-container": "#edeeef",
        "primary-container": "#ffd1dc",
        "on-primary-container": "#7a5761",
        "on-secondary-container": "#626374",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e4",
        "error": "#ba1a1a",
        "on-primary-fixed": "#2d141c",
        "on-background": "#191c1d",
        "surface-tint": "#78555e",
        "outline": "#817476",
        "tertiary-fixed-dim": "#9fcfd5",
        "on-primary-fixed-variant": "#5e3e47",
        "secondary": "#5c5d6e",
        "tertiary-fixed": "#bbebf1",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#1d4d53",
        "tertiary": "#37656b",
        "surface-variant": "#e1e3e4",
        "on-primary": "#ffffff",
        "primary": "#78555e",
        "error-container": "#ffdad6",
        "background": "#f8f9fa",
        "inverse-primary": "#e7bbc6",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#e7bbc6",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // background: "hsl(var(--background))", // Commented out to avoid conflict with above
        foreground: "hsl(var(--foreground))",
        // primary: {
        //   DEFAULT: "hsl(var(--primary))",
        //   foreground: "hsl(var(--primary-foreground))",
        // },
        // secondary: {
        //   DEFAULT: "hsl(var(--secondary))",
        //   foreground: "hsl(var(--secondary-foreground))",
        // },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "5px",
      },
      spacing: {
        "reader-width": "720px",
        "container-max": "1200px",
        gutter: "24px",
        unit: "8px",
        margin: "32px",
      },
      fontFamily: {
        "label-bold": ["Be Vietnam Pro", "Inter", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "Inter", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "Inter", "sans-serif"],
        "body-reading": ["Noto Serif", "Georgia", "serif"],
        "display-lg": ["Be Vietnam Pro", "Inter", "sans-serif"],
        "body-ui": ["Be Vietnam Pro", "Inter", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["13px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-reading": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-ui": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
